# importing library

In [16]:
import numpy as np

# Array Atrributes

In [17]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [18]:
type(a)

numpy.ndarray

In [19]:
a.shape

(5,)

In [20]:
a.ndim

1

In [21]:
b=np.array([[1,2,3],
           [4,5,6]])

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
type(b)

numpy.ndarray

In [24]:
b.shape

(2, 3)

In [25]:
b.ndim

2

In [27]:
c=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])

d=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
           
          [[10,11,12],
           [13,14,15],
           [16,17,18]]])


In [28]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
c.shape,d.shape

((1, 3, 3), (2, 3, 3))

In [30]:
a.dtype

dtype('int32')

In [31]:
a.dtype,b.dtype,c.dtype,d.dtype

(dtype('int32'), dtype('int32'), dtype('int32'), dtype('int32'))

In [32]:
a.size,b.size,c.size,d.size # dertermine how many elements are there in n array 

(5, 6, 9, 18)

In [ ]:
a.nbytes,b.nbytes,c.nbytes,d.nb